### ISSUE TITLE
centos7 - minicon-1.4-1 - /minicon/work/image.tar: permission denied

### ISSUE THREAD

**Issue by thelittlebug** [grycap/minicon#16]
hi,

tried as normal user and as root.
tried to create the dir /minicon/work.

does not work for me. am i missing something?

thanks and best regards
![image](https://user-images.githubusercontent.com/2874956/62564708-a599ec00-b885-11e9-8747-2bb6a569fee9.png)

**Comment by srisakthigajapathy** [comment]
Minicon 1-4.1 is not working
try older versions like 1-2.2.

**Comment by dealfonso** [comment]
I think that it is an issue with the CentOS version. I'll revise it.

**Comment by dealfonso** [comment]
Sorry, there was a problem when creating the packages. Now it is solved.

* I have tested it in a fresh CentOS 7 version with a fresh docker official installation.

Can you please try it?
