### ISSUE TITLE
Minicon 1-4.1 is not working properly

### ISSUE THREAD

**Issue by srisakthigajapathy** [grycap/minicon#17]
Minicon is extraordinary tool to reduce docker images size
When i used minicon 1-4.1 to reduce docker images it reduced centos images size to 0 B.But when i tried with 1-2.1 it is working perfectly.Kindly resolve the issues in 1-4.1.

**Comment by dealfonso** [comment]
Thank you for the report. Could you please include an example of Dockerfile and minicon commandline to reproduce the error?

**Comment by dealfonso** [comment]
Hi,

there was a problem in the packages. Now it has been solved.

@srisakthigajapathy, can you please lease try it?
